# Railway Configuration for API Server
apiVersion: v1
kind: ConfigMap
metadata:
  name: trustlens-api-config
data:
  NODE_ENV: "production"
  PORT: "3001"
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trustlens-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trustlens-api
  template:
    metadata:
      labels:
        app: trustlens-api
    spec:
      containers:
      - name: api
        image: node:18-alpine
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        workingDir: /app
        command: ["node", "server.js"]
        
---
apiVersion: v1
kind: Service
metadata:
  name: trustlens-api-service
spec:
  selector:
    app: trustlens-api
  ports:
  - port: 80
    targetPort: 3001
  type: LoadBalancer
